### ISSUE TITLE
[Feat] controller & view.html

### ISSUE THREAD

**Issue by Han-Jeong** [mm-spring/toy_spring#19]
# TODO
- [ ] make controller(user, board, comment, like)
- [ ] connect view(html)
- [ ] remove controller for assignment
